spring:
  datasource:
    url: jdbc:tc:mysql:8.4.8:///member_repository_jpa_integrationtest?TC_DAEMON=true&user=root&password=test&useInformationSchema=true
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: root
    password: test
  liquibase:
    change-log: classpath:/db/changelog/member/db.changelog-initial-schema.yaml
