CREATE DATABASE IF NOT EXISTS core;
CREATE DATABASE IF NOT EXISTS integration;

CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON core.* TO 'test'@'%';
GRANT ALL PRIVILEGES ON integration.* TO 'test'@'%';
FLUSH PRIVILEGES;
