name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version-file: .sdkmanrc

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: ./gradlew build -x test

      - name: Test
        run: ./gradlew test -i

      - name: Jacoco report
        run: ./gradlew jacocoRootReport

      - name: Upload coverage
        uses: madrapps/jacoco-report@v1.2
        with:
          title: 📝 테스트 커버리지 리포트입니다
          paths: ${{ github.workspace }}/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 85
